version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    ports:
     - "3000:3000"
    environment:
      - DB_HOST=mongo
